services:
  backend_pi_5:
    container_name: backend_pi_5_blue
    networks:
      - unified_network
    restart: unless-stopped
    image: ghcr.io/saians07/backend_pi_5:latest
    ports:
      - 8082:8080
    environment:
      - PORT=8080
    env_file:
      - ./.env

networks:
  unified_network:
    external: true