services:
  backend_pi_5_green:
    container_name: backend_pi_5_green
    networks:
      - unified_network
    restart: unless-stopped
    image: ghcr.io/saians07/backend_pi_5:latest
    ports:
      - 8083:8080
    env_file:
      - ./.env
    environment:
      - PORT=8080
      - APP_ENV=production
    command: ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-t", "10", "-w", "2", "-b", "0.0.0.0:8080", "--log-level", "debug", "main:app"]

networks:
  unified_network:
    external: true