services:
  backend_pi_5_blue:
    container_name: backend_pi_5_blue
    networks:
      - unified_network
    restart: unless-stopped
    image: ghcr.io/saians07/backend_pi_5:latest
    ports:
      - 8082:8080
    env_file:
      - ./.env
    environment:
      - PORT=8080
      - APP_ENV=production
    command: ["gunicorn", "-t", "10", "-w", "2", "-b", "0.0.0.0:8080", "--log-level", "debug", "main:app"]

networks:
  unified_network:
    external: true