"""Add unauthorized table

Revision ID: 0d9d300bcf45
Revises: d114396be229
Create Date: 2025-10-18 22:50:08.798997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9d300bcf45'
down_revision: Union[str, Sequence[str], None] = 'd114396be229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_unauthorized_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_tele_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('link_media', sa.String(length=250), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_datetime', sa.DateTime(), nullable=True),
    sa.Column('deleted_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('telegram_bot_chat_history', sa.Column('session_id', sa.String(length=100), nullable=False))
    op.add_column('telegram_bot_chat_history', sa.Column('text', sa.Text(), nullable=True))
    op.add_column('telegram_bot_chat_history', sa.Column('link_media', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_bot_chat_history', 'link_media')
    op.drop_column('telegram_bot_chat_history', 'text')
    op.drop_column('telegram_bot_chat_history', 'session_id')
    op.drop_table('telegram_unauthorized_user')
    # ### end Alembic commands ###
