"""Deskripsi perubahan skema

Revision ID: d114396be229
Revises: 
Create Date: 2025-10-17 00:46:43.392788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd114396be229'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_bot_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_tele_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_datetime', sa.DateTime(), nullable=True),
    sa.Column('deleted_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_tele_id')
    )
    op.create_table('telegram_bot_chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_datetime', sa.DateTime(), nullable=True),
    sa.Column('deleted_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['telegram_bot_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_bot_user_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('last_chat_datetime', sa.DateTime(), nullable=False),
    sa.Column('last_chat_summary', sa.String(length=2000), nullable=False),
    sa.Column('last_chat_update_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['telegram_bot_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_bot_user_summary')
    op.drop_table('telegram_bot_chat_history')
    op.drop_table('telegram_bot_user')
    # ### end Alembic commands ###
